### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by krlk89**
I've updated the README to be in compliance with Python 3 when using the next() function, nothing should break for Python 2.
Also added a sentence to notify the user about pysam dependency when wanting to use some functionality.
Problems described in #218 and #217.

### CODE REVIEW

**Comment by martijnvermaat** [comment]
Thanks @krlk89!

Looking for other occurences of `next` in the repository, two additional issues pop up:

1. The contents of `README.rst` are duplicated in the `vcf/__init__.py` docstring (and that's what you see [here](https://pyvcf.readthedocs.org/en/latest/INTRO.html). The two already seem to have deviated a bit. I'd say that the text can be removed from `vcf/__init__.py` and `docs/INTRO.rst` can use [include](http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment) the `README.rst` file.

2. Some utility code and unit tests still use the `.next()` method. I didn't investigate how the tests apparently still [pass on Python 3](https://travis-ci.org/jamescasbon/PyVCF/).

https://github.com/jamescasbon/PyVCF/search?utf8=%E2%9C%93&q=next

Let me know if you want to address these as well, otherwise I might have some time for it next week and merge this as-is.

**Comment by krlk89** [comment]
@martijnvermaat I will address the other occurrences sometime this week.

**Comment by krlk89** [comment]
@martijnvermaat I've made changes in all the files you listed except in docs/INTRO.rst. I don't know how (if) the include works, so I left it the way it is at the moment.

**Comment by martijnvermaat** [comment]
I went ahead and merged this together with some additional docs updates.

Many thanks @krlk89 !

**Pull request merged**
