### PR TITLE
add one more blacklist value

### PR DESCRIPTION
**Pull request by ericman93**

### CODE REVIEW

**Comment by sambrightman** [comment]
@martijnvermaat this looks like it should be closed in it's current state (no description, no tests, breaks tests, breaks FLAG INFO fields).

**Comment by martijnvermaat** [comment]
Agreed, thanks.

@ericman93 If you think this is needed, please explain why.

**Comment by ericman93** [comment]
I had a vcf with empty string as one of the info values.
In this senerio I got an exception.
Maybe it won't count as valid VCF, but I had to work with it.

**Comment by martijnvermaat** [comment]
The VCF spec leaves room for different interpretations I would say. PR with tests which doesn't break existing tests is always welcome.

**Comment by ericman93** [comment]
new PR with tests
https://github.com/jamescasbon/PyVCF/pull/264

**Pull request closed without merging**
