### PR TITLE
Fix for issue #140, add vcf_record_sort_key arg

### PR DESCRIPTION
**Pull request by bw2**
- Added 'vcf_record_sort_key' which allows users to specify any chromosome ordering.
- Fixed issue #140 by emitting all records from the current chromosome before moving on to the next one. This takes care of issue #140 in the typical case (when all files have records for all contigs), but still fails in some edge cases (when vcf files have differing sets of contigs and where the alphabetical order of these contigs is not the desired order). In those edge cases, the user can set the 'vcf_record_sort_key' arg to explicitly defining the chromosome order - in which case the issue would be completely solved.

### CODE REVIEW

**Comment by bw2** [comment]
Hi James, I wanted to sort VCF files and noticed this hasn't been merged. Would you be willing to merge these changes?
Thanks
-Ben

**Comment by martijnvermaat** [comment]
Hi @bw2, I'd have a look but it's not clear to me exactly which part of this PR is unmerged. Probably just [this commit](https://github.com/bw2/PyVCF/commit/10d9774)?

It doesn't apply cleanly on the current master branch (yes, it has been a while...). If you can rebase it, I can have a look.

**Comment by sambrightman** [comment]
@bw2 is this going to be cleaned up and rebased? Perhaps better to split off the new commits into a fresh PR and close this one?

**Comment by martijnvermaat** [comment]
Yes, at this point it would be better just to submit a new PR. We'd be happy to have it.

**Pull request closed without merging**
